### ISSUE TITLE
Missing GaugeRnR.html, (ubuntu subsystem windows 10, python3.6, pip install)

### ISSUE THREAD

**Issue by maidenone** [owodunni/GageRnR#31]
```
root@KDW10L21:~# GaugeRnR -d, -f /mnt/c/Users/anfo/Documents/resultTest2.csv -s 4,4,32 -o result
Traceback (most recent call last):
  File "/usr/local/bin/GaugeRnR", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/GaugeRnR/__main__.py", line 7, in main
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/GaugeRnR/application.py", line 116, in run
    rg.addDoc(g)
  File "/usr/local/lib/python3.6/dist-packages/GaugeRnR/reportGenerator.py", line 32, in addDoc
    doc = self.getObjectDoc(obj)
  File "/usr/local/lib/python3.6/dist-packages/GaugeRnR/reportGenerator.py", line 29, in getObjectDoc
    return self.readResource(type(obj).__name__ + '.html')
  File "/usr/local/lib/python3.6/dist-packages/GaugeRnR/reportGenerator.py", line 67, in readResource
    return resource_string('GaugeRnR.resources', filename).decode("utf-8")
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1149, in resource_string
    self, resource_name
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1393, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1516, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/GaugeRnR/resources/GaugeRnR.html'
```
For reference, i checked the expected folder:
```
root@KDW10L21:~# ls /usr/local/lib/python3.6/dist-packages/GaugeRnR/resources/
__init__.py  __pycache__  bootstrap.min.css
```

Fix:
```
 cd /usr/local/lib/python3.6/dist-packages/GaugeRnR/resources/
 wget https://raw.githubusercontent.com/owodunni/GageRnR/master/GageRnR/resources/GageRnR.html
 wget https://raw.githubusercontent.com/owodunni/GageRnR/master/GageRnR/resources/Linearity.html
 wget https://raw.githubusercontent.com/owodunni/GageRnR/master/GageRnR/resources/Normality.html
 wget https://raw.githubusercontent.com/owodunni/GageRnR/master/GageRnR/resources/Statistics.html
 mv GageRnR.html GaugeRnR.html

```

**Comment by owodunni** [comment]
Hi, I think you are using the wrong lib. It seams like you are using the old library. Trying installing the new one with 

```pip install GageRnR```
